# 3. 流程控制、循环语句、异常处理、函数的高级用法

## Python 的逻辑控制语句

### 条件控制语句

![条件控制语句](https://ss.im5i.com/2020/12/26/-2.png)

* `if` & `else`

  ```python
  x = 4
  if x % 2 == 0:
      print("x 是偶数")
  ```

  

* `if` & `else if` & `else`

  ```python
  x = 5
  if x > 30:
      print("x > 30")
  elif 3 < x <= 30: # elif ==> else if
      print("3 < x <= 30")
  else:
      print("x <= 3")
  ```


### 循环语句

* `for`

  遍历一个可迭代对象(可理解为 `list` )，会影响相同作用域当中的变量

  ```python
  q = [3, 7, 2, 6, 0, 1]
  for item in q:
      print(item)
  ```

  * 获取索引值和值

    ```python
    q = [1, 2, 3, 4, 5, 6, 7]
    
    for idx, value in enumerate(q):
        print(f"index : {idx}, value : {value}")
    ```

* `while`

  必须要有 **退出机制** (一定要有逻辑判断语句来退出 `while`)

  > while 判断语句:
  >
  > ​	循环体

  > while True:
  >
  > ​	判断语句
  >
  > ​	循环体

  ```python
  counter = 0
  while True:
      if counter == 100:
          break
      print(f"sim process : {counter}")
      counter += 1
  #######################################
  counter = 0
  while counter < 100:
      print(f"sim process : {counter}")
      counter += 1
  ```

* 跳出循环

  * `break`

    停止当前循环，不再执行循环

  * `continue`

    跳过当前循环执行下一次循环

  * `pass`

    跳过当前条件判断语句中的执行语句，后续语句继续执行

    ```python
    l = [1, 2, 3, 54, 6, 7]
    for item in l:
        if item == 3:
            pass
            # continue
        else:
            print(f"serach item: {item}")
        print("-------------------------------------")
    ```


## Python 的异常与处理

### 异常

程序遇到严重错误时，会终止程序的运行并抛出异常

```python
def my_div(a, b):
    return a / b


if __name__ == "__main__":
    my_div(1, 0)


Traceback (most recent call last):
  File "C:\Users\Jerryiweb\PycharmProjects\study\main.py", line 6, in <module>
    my_div(1, 0)
  File "C:\Users\Jerryiweb\PycharmProjects\study\main.py", line 2, in my_div
    return a / b
ZeroDivisionError: division by zero
```

### 捕获异常

> try:
>
> ​    表达式
>
> except [Exception] as e:
>
> ​    表达式
>
> finally:
>
> ​	表达式

```python
def my_div(a, b):
    try:
        return a / b
    except Exception as e:
        print("分母不能为零")
        print(f"报错信息： {e}")
        return None
    finally:
        print("function my_div end")


if __name__ == "__main__":
    my_div(1, 0)


分母不能为零
报错信息： division by zero
function my_div end
```

* Exception

  > 所有异常的基类，所有异常都是 Exception 的子类。

  一般不直接捕获 **Exception** ，尤其是**数据处理**时。

* 常见异常

  * IndexError

    索引值超过了列表长度

    ```python
    >>> l = [1]
    >>> l
    [1]
    >>> l[2]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: list index out of range
    ```

  * KeyError

    找不到 `Key`

    ```python
    >>> d = {"a" : 1}
    >>> d["b"]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    KeyError: 'b'
    ```

  * ValueError

    传入的参数错误

    ```python
    >>> int("a1")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: invalid literal for int() with base 10: 'a1'
    ```

  * TypeError

    类型错误，常见于运算

    ```python
    >>> 1 + '2'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unsupported operand type(s) for +: 'int' and 'str'
    ```

  * SyntaxError

    语法错误

    ```python
    >>> a+++
      File "<stdin>", line 1
        a+++
            ^
    SyntaxError: invalid syntax
    ```

    
